[project]
name = "vidz"
version = "0.1.0"
description = "Video analysis project using Pixeltable"
requires-python = ">=3.10"
dependencies = [
    "pytube",
    "pixeltable @ git+https://github.com/mkornacker/pixeltable.git@tracker",
    "scenedetect",
    "opencv-python",
    "spacy",
    "sentence-transformers",
    "ipykernel",
    "ipywidgets",
    "pip",
    "openai-whisper",
    "google-genai",
]

